services:
  client-0:
    build:
      context: .
      dockerfile: Containerfile
    container_name: speer-client-0
    ports:
      - "3000:3000"
      - "5173:5173"
    restart: "no"
  client-1:
    build:
      context: .
      dockerfile: Containerfile
    container_name: speer-client-1
    ports:
      - "3001:3000"
      - "5174:5173"
    restart: "no"
 
