services:
  client:
    build: ./client
    container_name: client-speer
    ports:
      - "3000:3000"
    restart: always
  server:
    build: ./server
    container_name: server-speer
    ports:
      - "8000:8000"
    restart: always

