services:
  server-0:
    build:
      context: ./supernode_comms
      dockerfile: Containerfile
    container_name: speer-server-0
    environment:
      SERVER_NODE_NAME: 'speer-server-0'
    ports:
      - "8000:8000"
    restart: "no"
  server-1:
    build:
      context: ./supernode_comms
      dockerfile: Containerfile
    container_name: speer-server-1
    environment:
      SERVER_NODE_NAME: 'speer-server-1'
    ports:
      - "8001:8000"
    restart: "no"
  server-2:
    build:
      context: ./supernode_comms
      dockerfile: Containerfile
    container_name: speer-server-2
    environment:
      SERVER_NODE_NAME: 'speer-server-2'
    ports:
      - "8002:8000"
    restart: "no"
  client-0:
    environment:
        SUPERNODE_URL: 'ws://localhost:8000'
    build:
      context: ./client
      dockerfile: Containerfile
    container_name: speer-client-0
    ports:
      - "3000:3000" # video listening?
      - "5173:5173" # web ui for using this client
    restart: "no"
  client-1:
    environment:
        SUPERNODE_URL: 'ws://localhost:8001'
    build:
      context: ./client
      dockerfile: Containerfile
    container_name: speer-client-1
    ports:
      - "3001:3000"
      - "5174:5173" # web ui
    restart: "no"
 
